### ISSUE TITLE
timeout not handled when sending transactional emails

### ISSUE THREAD

**Issue by FreeWillaert** [mailin-api/sendinblue-nodejs-api-npm#4]
I'm switching to this library because mailin-api-node-js doesn't support timeouts - and seems to end up in a broken state in case of a timeout.

However, I seems that this library does not handle timeouts either - or at least not correctly.

See code sample below: when I force a timeout by setting a very low value (100ms), the callback is never called. Frankly, I'm not even sure what exactly happens.

```
    var sendinblue = require('sendinblue-api');
    var parameters = { "apiKey": sendInBlueApiKey, "timeout": 100 };
    var sendinObj = new sendinblue(parameters);
    var input = {
        "id": 1,
        "to": sendInBlueToEmail,
        "attr": { Name: "JohnDoe", Phone: "1234", Email: sendInBlueToEmail }
    };
    console.log("sending email...");
    sendinObj.send_transactional_template(input, function (err, response) {
        if (err) {
            console.error(err); // in case of timeout, we never get here...
        }
        console.log(response); // ...nor here...!
    });

```

Can you please confirm this as a bug, or tell me what is wrong with my code?

**Comment by ekta-slit** [comment]
Hello @FreeWillaert 

Thank you for contacting us.

The [mailin-api-node-js](https://github.com/mailin-api/mailin-api-node-js/tree/master/V2.0) V2.0 library do supports timeout.
The default timeout value is 30,000 MS ( 30 Sec ), and maximum allowed timeout value is 60,000 MS ( 60 Sec ). 

Since you passed 100 MS ( 0.1 Sec ), which is actually a very low value & won't let you complete the request.
Please use at least 2000 MS ( 2 Sec ) & transactional email will be good to go.

Regards,
Sendinblue Team

**Comment by ekta-slit** [comment]
Hello again @FreeWillaert,

In addition to your query, we have also updated our library by adding timeout callback :)

Thank you,
Sendinblue Team
