### ISSUE TITLE
not able to send transaction template email

### ISSUE THREAD

**Issue by ShahnazK** [mailin-api/sendinblue-nodejs-api-npm#8]
i am using this api `send_transactional_template` to send the template as a transnational email. i don't get any error but mail is not delivered. i am getting the following response - 
`{ code: 'success', message: 'Updated the Template.', data: [] }`
It seems there is an error and it is calling update template api rather than sending the transaction template mail.

**Comment by ekta-slit** [comment]
Hello @ShahnazK 

Thank you for contacting us.
The issue is happening because you are redefining some parameters already defined in the template.
For your particular case it could be `subject` or `from` which are invalid input parameter for [send_transcational_template](https://apidocs.sendinblue.com/template/#1) API.

Regards
SendinBlue Team
